version: '3.1'

services:
  my_php:
    build: ./php
    container_name: my_php
    volumes:
      - ../server:/var/www/html
    ports:
      - 8181:80
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_MEMORY_LIMIT: 2G
      PHP_UPLOAD_MAX_FILESIZE: 512M
      PHP_POST_MAX_SIZE: 512M
      PHP_DISPLAY_ERRORS: 1
      php.xdebug.max_nesting_level: 500
    depends_on:
      - my_mysql

  my_mysql:
    build: ./mysql
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: cbece_gead-cebfa
      MYSQL_DATABASE: my_mysql
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp
    ports:
      - 3131:3306
    volumes:
      - my-db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - my_mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8008:80'
    environment:
      PMA_HOST: 'my_mysql'
      MYSQL_ROOT_PASSWORD: 'cbece_gead-cebfa'

volumes:
  my-db: